apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-job-ui
  labels:
    app: training-job-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-job-ui
  template:
    metadata:
      labels:
        app: training-job-ui
    spec:
      containers:
        - name: training-job-ui
          image: docker.io/loihoangthanh1411/kf-training-job:v0.10
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: training-job-ui
  labels:
    app: training-job-ui
spec:
  type: NodePort
  selector:
    app: training-job-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32010
